### ISSUE TITLE
Entity Subheader

### ISSUE THREAD

**Issue by mastersilv3r** [Mindgreppers/OHHDL#13]
Link
Read Permission: Guest can read or not checkbox
Trash
History of entity: Creation time, last updated, comments. This will open a new window of type: 'Entity history' and title: '{EntityType}: {EntityTitle}'

**Comment by vaibhavmule** [comment]
Add Trash icon and Guest can see Checkbox.
Last Updated by {{user}} {{time}} ago. 
{{N}} comments.

**Comment by vaibhavmule** [comment]
Last Update and {{N}} comments will be in Moderation flow.
