### ISSUE TITLE
link: search and link

### ISSUE THREAD

**Issue by mastersilv3r** [Mindgreppers/OHHDL#9]
There will be a link button in the window subheader for entities. 
Will open a drop down to select entity type and a search box.
User selects entity type to link to, and types search query in search box and presses search.
A window opens up search results for selected entity type. User can click on any results to add them to 'to be linked' set. User can also click on  link all to add all the results to 'to be linked' set.

In fact, any entities currently showed on the page, or any entities loaded on the page subsequently, will show the 'link' button on their subheader.

While user is adding things to 'to be linked' set, a count of the number of items in the set is shown in the subheader of the main entity, with option to cancel linking and done linking.

After user is done with linking, he goes back to the main entity page, and says 'Linking Done'. If in meantime user wants to cancel the linking, he will click on 'Cancel Linking' on window subheader. 

If user wants to see details of an entity in search result, he can open that entity, and that window subheader will also show option of linking.

**Comment by vaibhavmule** [comment]
Color coding for Entity in Window Header.

**Comment by vaibhavmule** [comment]
Also Dual linking
